images/urls.py
'''
Created on May 9, 2012

@author: pvergil
'''

from django.conf.urls.defaults import patterns, url
from django.contrib.auth.decorators import login_required

from images.views import NewPhotos, Crop

newPhotos = login_required(NewPhotos.as_view())
crop = login_required(Crop.as_view())

urlpatterns = patterns('',
    url(r'^new-photos/$', newPhotos, name='images_newphotos'),
    url(r'^crop/$', crop, name='images_crop'),
)

post/urls.py
'''
Created on Jul 19, 2012

@author: pvergil
'''

from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from post.views import AddImage, AddPost, AllPost, AddView, ViewView

_all = AllPost.as_view()
_new = AddPost.as_view()
_img = AddImage.as_view()

_img = csrf_exempt(_img)

_add = login_required(AddView.as_view())
_view = ViewView.as_view()

urlpatterns = patterns('',
    url(r'^$', _all, name='post_all'),
    url(r'^add/$', _add, name='post_add'),
    url(r'^new/$', _new, name='post_new'),
    url(r'^img/$', _img, name='post_img'),
    url(r'^(?P<pid>\d+)/$', _view, name='post_view'),
)

uploadify/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^adventure/', include('adventure.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^uploader/', include('uploader.urls')),
    url(r'^images/', include('images.urls')),
    url(r'^imahe/', include('imahe.urls')),
    url(r'^post/', include('post.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),
)

# Serve user-uploaded files
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

images/models.py
import os

from django.contrib.auth.models import User
from django.db import models
from django.utils.dateformat import format

from uploadify.lib.utils import get_random_string

def image_upload(instance, filename):
    return _upload(instance, filename, 'uploads/%d/image/%s%s')

def thumb_upload(instance, filename):
    return _upload(instance, filename, 'uploads/%d/thumb/%s%s')

def _upload(instance, filename, path):
    file_nm, file_ex = os.path.splitext(filename)
    return path % (instance.owner.id, get_random_string(), file_ex)

STATUS_CHOICES = (
    ('N', 'New'),
    ('C', 'Cropped'),
)

class Image(models.Model):
    owner = models.ForeignKey(User)
    image = models.ImageField(upload_to=image_upload)
    thumb = models.ImageField(upload_to=thumb_upload)
    stats = models.CharField(max_length=1, choices=STATUS_CHOICES, default='N')
    date  = models.DateTimeField(auto_now_add=True)

images/views.py
from django.http import HttpResponseForbidden
from django.views.generic import ListView, View
from django.shortcuts import get_object_or_404

from images.models import Image
from uploadify.lib import imaging, utils

class NewPhotos(ListView):
    template_name = 'images/new-photos.html'
    
    def get_queryset(self):
        images = Image.objects.filter(owner=self.request.user, stats='N')
        return images 
    
class Crop(View):
    
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return HttpResponseForbidden()
        
        id = request.POST.get('id')
        
        x1 = int(float(request.POST.get('x1')))
        y1 = int(float(request.POST.get('y1')))
        x2 = int(float(request.POST.get('x2')))
        y2 = int(float(request.POST.get('y2')))
        
        img = get_object_or_404(Image, id=id)
        
        imaging.crop(img.image.path, (x1, y1, x2, y2))
        imaging.crop(img.thumb.path, (x1, y1, x2, y2))
        
        img.stats = 'C'
        img.save()
        
        return utils.jsonResponse({
            'status': 'OK'
        })

images/templates/images/new-photos.html
{% extends "base.html" %}

{% block head_extras %}
	{% load staticfiles %}
	<!-- Jcrop CSS -->
	<link type="text/css" rel="stylesheet" href="{% static 'imahe/css/jcrop/jquery.jcrop.css' %}" />
	<!-- Jcrop CSS -->
	
	<!-- Jcrop JS -->
	<script type="text/javascript" src="{% static 'imahe/js/jcrop/jquery.jcrop.js' %}"></script>
	<!-- Jcrop JS -->
	
	<style type="text/css">
	.form-horizontal .control-label {
		width: 20px;
	}
	
	.form-horizontal .controls {
		margin-left: 40px;
	}
	.form-horizontal .form-actions {
		padding-left: 40px;
	}
	
	.form-actions {
		background: none;
	}
	</style>
	
	<script type="text/javascript">
	$(function() {
		function onSelect(c, form) {
			form.find('.x1').val(parseInt(c.x));
			form.find('.y1').val(parseInt(c.y));
			form.find('.x2').val(parseInt(c.x2));
			form.find('.y2').val(parseInt(c.y2));
			form.find('.w').val(parseInt(c.w));
			form.find('.h').val(parseInt(c.h));
		}
		
		function onSubmit(e, form) {
			$.post('{% url images_crop %}', form.serialize(), function(response) {
			});
		}
		
		$('.uploaded-photo').each(function(i, obj) {
			$(this).load(function() {
				var $this = $(this);
				
				var src = $this.attr('src');
				
				var img = $('<img/>').attr('src', src).load(function() {
					var w = this.width;
					var h = this.height;
					
					$.Jcrop('#jc_image'+i, {
						onChange: function(c) {
							onSelect(c, form);
						},
						onSelect: function(c) {
							onSelect(c, form);
						},
						aspectRatio: 1,
						trueSize: [w, h],
						minSize: [150, 150]
					});
				});
			});
			
			var form = $('#form'+i);
			
			form.submit(function(e) {
				e.preventDefault();
				onSubmit(e, form);
			});
		});
	}); 
	</script>
{% endblock head_extras %}

{% block content %}
	{% for photo in image_list %}
	<div class="my-row unwell">
		<div class="row-fluid show-grid">
			<div class="span8">
				<img src="{{ photo.image.url }}" class="uploaded-photo" id="jc_image{{ forloop.counter0 }}" />
			</div>
			<div class="span4">
				<form id="form{{ forloop.counter0 }}" class="form-horizontal">
					<input type="hidden" name="id" value="{{ photo.id }}" />
					<input type="hidden" name="x2" value="0" class="x2" />
					<input type="hidden" name="y2" value="0" class="y2" />
					
					<div class="control-group">
						<label class="control-label" for="x1{{ forloop.counter0 }}">X</label>
						<div class="controls">
							<input type="text" name="x1" value="0" class="disabled x1" id="x1{{ forloop.counter0 }}" readonly="readonly" />
						</div>
					</div>
					
					<div class="control-group">
						<label class="control-label" for="y1{{ forloop.counter0 }}">Y</label>
						<div class="controls">
							<input type="text" name="y1" value="0" class="disabled y1" id="y1{{ forloop.counter0 }}" readonly="readonly" />
						</div>
					</div>
					
					<div class="control-group">
						<label class="control-label" for="w{{ forloop.counter0 }}">W</label>
						<div class="controls">
							<input type="text" name="w" value="0" class="disabled w" id="w{{ forloop.counter0 }}" readonly="readonly" />
						</div>
					</div>
					
					<div class="control-group">
						<label class="control-label" for="h{{ forloop.counter0 }}">H</label>
						<div class="controls">
							<input type="text" name="h" value="0" class="disabled h" id="h{{ forloop.counter0 }}" readonly="readonly" />
						</div>
					</div>
					
					<div class="form-actions">
						<input type="submit" value="Crop Image" class="btn btn-large btn-primary" />
					</div>
				</form>
			</div>
		</div>
	</div>
	{% endfor %}
{% endblock content %}