imahe/urls.py
'''
Created on May 21, 2012

@author: pvergil
'''

from django.conf.urls.defaults import patterns, url
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from imahe.views import Gallery, ImageEditor, ImageViewer, Upload, Crop

gallery = login_required(Gallery.as_view())
upload = login_required(Upload.as_view())
crop = login_required(Crop.as_view())

viewer = login_required(ImageViewer.as_view())
editor = login_required(ImageEditor.as_view())

upload = csrf_exempt(upload)

urlpatterns = patterns('',
    url(r'^gallery/$', gallery, name='imahe_gallery'),
    url(r'^upload/$', upload, name='imahe_upload'),
    url(r'^crop/$', crop, name='imahe_crop'),
    
    url(r'^view/(?P<pk>\d+)/$', viewer, name='imahe_viewer'),
    url(r'^edit/(?P<pk>\d+)/$', editor, name='imahe_editor'),
)

post/urls.py
'''
Created on Jul 19, 2012

@author: pvergil
'''

from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from post.views import AddImage, AddPost, AllPost, AddView, ViewView

_all = AllPost.as_view()
_new = AddPost.as_view()
_img = AddImage.as_view()

_img = csrf_exempt(_img)

_add = login_required(AddView.as_view())
_view = ViewView.as_view()

urlpatterns = patterns('',
    url(r'^$', _all, name='post_all'),
    url(r'^add/$', _add, name='post_add'),
    url(r'^new/$', _new, name='post_new'),
    url(r'^img/$', _img, name='post_img'),
    url(r'^(?P<pid>\d+)/$', _view, name='post_view'),
)

uploadify/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^adventure/', include('adventure.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^uploader/', include('uploader.urls')),
    url(r'^images/', include('images.urls')),
    url(r'^imahe/', include('imahe.urls')),
    url(r'^post/', include('post.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),
)

# Serve user-uploaded files
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

imahe/models.py
import os
import datetime

from django.contrib.auth.models import User
from django.db import models

from uploadify.lib.utils import get_random_string

def image_upload(instance, filename):
    return _upload(instance, filename, 'uploads/%d/images/%d/%d/%d/%s%s')

def thumb_upload(instance, filename):
    return _upload(instance, filename, 'uploads/%d/thumbs/%d/%d/%d/%s%s')

def _upload(instance, filename, path):
    today = datetime.datetime.now()
    file_nm, file_ex = os.path.splitext(filename)
    return path % (instance.owner.id, today.year, today.month, today.day, get_random_string(), file_ex)

STATUS_CHOICES = (
    ('N', 'New'),
    ('C', 'Cropped'),
)

class Photo(models.Model):
    owner = models.ForeignKey(User)
    image = models.ImageField(upload_to=image_upload)
    thumb = models.ImageField(upload_to=thumb_upload)
    title = models.CharField(max_length=160, default='Untitled')
    description = models.CharField(max_length=255, blank=True, null=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='N')
    date = models.DateTimeField(auto_now_add=True)

class Imahe(models.Model):
    owner = models.ForeignKey(User)
    image = models.ImageField(upload_to=image_upload)
    thumb = models.ImageField(upload_to=thumb_upload)
    stats = models.CharField(max_length=1, choices=STATUS_CHOICES, default='N')
    date  = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    desc  = models.CharField(max_length=255, blank=True, null=True)

imahe/forms.py
'''
Created on Jun 11, 2012

@author: pvergil
'''

from django import forms

from imahe.models import Photo

class PhotoEditorForm(forms.ModelForm):
    title = forms.CharField(label='Title', widget=forms.TextInput(attrs={'placeholder': 'Photo title'}),
                            error_messages={'required': 'Please enter a title for this photo.'})
    description = forms.CharField(label='Description', widget=forms.Textarea(attrs={'placeholder': 'Photo Description'}),
                            required=False)
    
    class Meta:
        model = Photo
        fields = ('title', 'description',)

imahe/views.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, TemplateView
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect

from imahe.forms import PhotoEditorForm
from imahe.models import Photo
from uploadify.lib import imaging, utils

class Gallery(ListView):
    template_name = 'imahe/gallery.html'
    
    def get_queryset(self):
        return Photo.objects.filter(owner=self.request.user) 

class Upload(TemplateView):
    template_name = 'imahe/upload.html'
    
    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context['session_nm'] = settings.SESSION_COOKIE_NAME
        context['session_ky'] = request.session.session_key
        return self.render_to_response(context)
    
    def post(self, request, *args, **kwargs):
        user = request.user
        
        if user.is_authenticated():
            data = request.FILES['Filedata']
            
            photo = Photo.objects.create(image=data, thumb=data, owner=user)
            # Resize the photo so it has a width of 620 pixels
            imaging.resizeWidth(photo.image.path)
            # Resize the thumbnail to 180x180 pixels
            imaging.fit(photo.thumb.path)
            
            return utils.jsonResponse({
                'redirect': reverse('imahe_editor', args=[photo.id]),
                'message': 'Photo uploaded',
                'status': 'OK'
            })
        else:
            return HttpResponseForbidden()
        
class Crop(TemplateView):
    template_name = 'imahe/crop.html'
    
    def post(self, request, *args, **kwargs):
        user = request.user
        
        if user.is_authenticated():
            id = request.POST.get('id')
            
            x1 = int(float(request.POST.get('x1')))
            y1 = int(float(request.POST.get('y1')))
            x2 = int(float(request.POST.get('x2')))
            y2 = int(float(request.POST.get('y2')))
            
            img = get_object_or_404(Photo, id=id)
            
            imaging.crop(img.image.path, (x1, y1, x2, y2))
            imaging.crop(img.thumb.path, (x1, y1, x2, y2))
            
            img.stats = 'C'
            img.save()
            
            return utils.jsonResponse({
                'status': 'OK'
            })
        else:
            return HttpResponseForbidden()
        
class ImageViewer(DetailView):
    template_name = 'imahe/viewer.html'
    context_object_name = 'photo'
    model = Photo

class ImageEditor(TemplateView):
    template_name = 'imahe/editor.html'
    
    def get_context_data(self, **kwargs):
        photo = get_object_or_404(Photo, pk = kwargs.get('pk'))
        form = PhotoEditorForm(instance=photo)
        return {
            'photo': photo,
            'form': form
        }
        
    def post(self, request, *args, **kwargs):
        photo = get_object_or_404(Photo, pk=kwargs.get('pk'))
        form = PhotoEditorForm(request.POST, instance=photo)
        
        if form.is_valid():
            title = form.cleaned_data.get('title')
            descr = form.cleaned_data.get('description')
            
            photo.description = descr
            photo.title = title
            photo.save()
            
            return redirect(
                'imahe_viewer',
                kwargs.get('pk')
            )
            
        return self.render_to_response({
            'photo': photo,
            'form': form
        })

imahe/templates/imahe/editor.html
{% extends "base.html" %}

{% block content %}
	<div class="row-fluid">
		<div class="span8">
			<img alt="" src="{{ photo.image.url }}" alt="{{ photo.title }}" />
		</div>
		<div class="span4">
			<form method="post">
				<div>
					{{ form.title }}
					{% for error in form.title.errors %}
						<p class="alert alert-error">{{ error }}</p>
					{% endfor %}
				</div>
				<div>
					{{ form.description }}
					{% for error in form.description.errors %}
						<p class="alert alert-error">{{ error }}</p>
					{% endfor %}
				</div>
				<div>
					<input type="submit" value="SAVE" class="btn btn-large btn-primary" />
				</div>
				{% csrf_token %}
			</form>
		</div>
	</div>
{% endblock content %}

imahe/templates/imahe/gallery.html
{% extends "base.html" %}

{% block head_extras %}
	{% load staticfiles %}
	<!-- Jcrop CSS -->
	<link type="text/css" rel="stylesheet" href="{% static 'imahe/css/jcrop/jquery.jcrop.css' %}" />
	<!-- Jcrop CSS -->
	
	<!-- Jcrop JS -->
	<script type="text/javascript" src="{% static 'imahe/js/jcrop/jquery.jcrop.js' %}"></script>
	<!-- Jcrop JS -->
{% endblock head_extras %}

{% block content %}
	<ul class="thumbnails">
	{% for photo in photo_list %}
		<li class="span2">
			<div class="thumbnail">
				<a href="{% url imahe_viewer pk=photo.id %}">
					<img alt="" src="{{ photo.thumb.url }}" />
				</a>
				<div class="caption">
					<h5>{{ photo.title }}</h5>
					<div class="actions">
						<a class="btn btn-mini pull-right" href="{% url imahe_editor pk=photo.id %}" title="Edit">
							<i class="icon-remove"></i>
						</a>
						
						<a class="btn btn-mini pull-right" href="{% url imahe_editor pk=photo.id %}" title="Delete">
							<i class="icon-edit"></i>
						</a>
					</div>
				</div>
			</div>
		</li>
	{% empty %}
		<li>
			<p>No photos available.</p>
		</li>
	{% endfor %}
	</ul>
{% endblock content %}

imahe/templates/imahe/upload.html
{% extends "base.html" %}

{% block head_extras %}
	{% load staticfiles %}
	<!-- Uploadify CSS -->
	<link type="text/css" rel="stylesheet" href="{% static 'imahe/css/uploadify/uploadify.css' %}" />
	<!-- Uploadify CSS -->
	
	<!-- Uploadify JS -->
	<script type="text/javascript" src="{% static 'imahe/js/uploadify/uploadify.js' %}"></script>
	<!-- Uploadify JS -->
	
	<script type="text/javascript">
	$(function() {
		var formData = {
			'{{ session_nm }}': '{{ session_ky }}'
		};
		
		$('#file_upload').uploadify({
			'swf'             : "{% static 'imahe/js/uploadify/uploadify.swf' %}",
			'uploader'        : "{% url imahe_upload %}",
			'fileTypeExts'    : '*.gif; *.jpg; *.png',
			'fileTypeDesc'    : 'Image File',
			'formData'        : formData,
			'multi'           : false,
			'onUploadSuccess' : function(event, data) {
				var data = $.parseJSON(data);
				window.location = data.redirect;
			}
		});
	}); 
	</script>
{% endblock head_extras %}

{% block content %}
	<input type="file" name="file_upload" id="file_upload" />
{% endblock content %}

imahe/templates/imahe/uploadify_button.html
<input type="file" name="file_upload" id="file_upload" />

imahe/templates/imahe/uploadify_dependencies.html
{% load staticfiles %}
<!-- Uploadify CSS -->
<link type="text/css" rel="stylesheet" href="{% static 'imahe/css/uploadify/uploadify.css' %}" />
<!-- Uploadify CSS -->

<!-- Uploadify JS -->
<script type="text/javascript" src="{% static 'imahe/js/uploadify/uploadify.js' %}"></script>
<!-- Uploadify JS -->

imahe/templates/imahe/uploadify_script.html
<script>
jQuery(function($) {
	var formData = {
		'{{ session_nm }}': '{{ session_ky }}'
	};
	$('{{ css_selector }}').uploadify({
		'swf'             : "{% static 'imahe/js/uploadify/uploadify.swf' %}",
		'uploader'        : "{% url imahe_upload %}",
		'fileTypeExts'    : '*.gif; *.jpg; *.png',
		'fileTypeDesc'    : 'Image File',
		'formData'        : formData,
		'multi'           : false,
		'onUploadSuccess' : function(event, data) {
			var data = $.parseJSON(data);
			window.location = data.redirect;
		}
	});
});
</script>

imahe/templates/imahe/viewer.html
{% extends "base.html" %}

{% block content %}
	<div class="row-fluid">
		<div class="span8">
			<img alt="" src="{{ photo.image.url }}" alt="{{ photo.title }}" />
		</div>
		<div class="span4">
			<h3>{{ photo.title }}</h3>
			<p>
				{% if photo.description %}
					{{ photo.description }}
				{% else %}
					No photo description.
				{% endif %}
			</p>
		</div>
	</div>
{% endblock content %}